---
title: "Panicum hallii microbiome"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidyMB)
```

```{r}
ct <- readRDS("~/SGMB/Albina//PH_Analysis/count_table.rds") %>% 
  t() %>% as.data.frame() %>% rownames_to_column("sequence") %>% as_tibble()
taxa <- readRDS("~/SGMB/Albina/PH_Analysis/taxa.rds") %>% 
  as.data.frame() %>% rownames_to_column("sequence") %>% as_tibble()
map <- read.table("~/SGMB/Albina/PH_Analysis/map.txt") %>% 
  mutate(SampleID = gsub("\\.fastq\\.gz", "", V2))
```

```{r}
ph_data <- ct %>% 
  gather(SampleID, value, -sequence) %>% 
  inner_join(taxa, by = "sequence") %>% 
  inner_join(map, by = "SampleID") %>% 
  filter(Family != "Mitochondria" & Order != "Chloroplast" & Kingdom != "Eukaryota") %>% 
  group_by(SampleID) %>% 
  mutate(depth = sum(value), RA = value / depth) %>% 
  mutate(Phylum2 = NA) %>% 
  mutate(Phylum2 = ifelse(Phylum == "Proteobacteria", as.character(Class), as.character(Phylum)))
```


```{r}
ph_data %>% 
  group_by(SampleID, Phylum2) %>% 
  summarise(phy_total = sum(RA)) %>% 
  group_by(Phylum2) %>% 
  nest() %>% 
  mutate(total = map_dbl(data, ~sum(.x$phy_total, na.rm = T))) %>% 
  top_n(10, total) %>% 
  unnest(data) %>% 
  ggplot(aes(SampleID, phy_total, fill = Phylum2)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Spectral")
```

```{r}
ph_data %>% 
  filter(grepl("FIL", V1) | grepl("HAL", V1)) %>% 
  separate(V1, into = c("Genotype", "number", "Comp"), sep = "\\.") %>% 
  separate(Comp, into = c("Comp", "Year", "Rep")) %>% 
  group_by(1) %>% 
  nest() %>% 
  mutate(pc = map(data, ~tidy_pcoa(samples = "SampleID", otus = "sequence")))
  group_by(SampleID, Phylum2, Genotype, Comp) %>% 
  summarise(phy_total = sum(RA)) %>% 
  group_by(Phylum2) %>% 
  nest() %>% 
  mutate(total = map_dbl(data, ~sum(.x$phy_total, na.rm = T))) %>% 
  top_n(10, total) %>% 
  unnest(data) %>% 
  ggplot(aes(SampleID, phy_total, fill = Phylum2)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Spectral") +
  facet_grid(.~Genotype + Comp, space = "free", scales = "free")
```

